export const chapterVideos = {
  "instrument": {
    "id": "ti5mo0REUTk",
    "title": "Piano Posture and Hand Shape | Beginners Start Here!",
    "author": "PianoTips",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Pemula absolut",
    "focus": "Duduk dan bentuk tangan yang nyaman",
    "ready": "Belum perlu membaca not atau akor.",
    "watch": "Perhatikan tinggi bangku dan posisi pergelangan; jangan meniru bentuk tangan secara paksa.",
    "task": "Atur posisi lalu mainkan lima nada perlahan. Catat apakah gerak nyaman.",
    "start": 0
  },
  "keys": {
    "id": "4__cIAvrWHw",
    "title": "How To Play Piano (Your First Piano Lesson) 🥇",
    "author": "Pianote",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Pemula absolut",
    "focus": "Mengenali tuts sebelum mencoba akor",
    "ready": "Kenali pola dua dan tiga tuts hitam.",
    "watch": "Mulai dari pengenalan keyboard; bagian akor boleh ditonton sebagai pengantar, bukan target kecepatan.",
    "task": "Temukan C di tiga oktaf, sebut nomor jari, lalu mainkan C–D–E–F–G.",
    "start": 0
  },
  "pulse": {
    "id": "_LipFNI8Ilo",
    "title": "BELAJAR KETUKAN PADA NOT BALOK - NOT BALOK DASAR | BELAJAR PIANO INDONESIA",
    "author": "Erika Oei",
    "checked": "2026-10-06",
    "language": "Indonesia",
    "level": "Pemula absolut",
    "focus": "Ketukan dasar",
    "ready": "Dapat memainkan satu nada.",
    "watch": "Dengarkan perbedaan panjang nada; tepuk dulu sebelum memakai piano.",
    "task": "Tepuk empat ketuk, lalu mainkan C empat kali tanpa mempercepat.",
    "start": 0
  },
  "staff": {
    "id": "OtbgZrEbbWs",
    "title": "CARA MUDAH MEMBACA NOT BALOK | BELAJAR PIANO INDONESIA",
    "author": "Erika Oei",
    "checked": "2026-10-06",
    "language": "Indonesia",
    "level": "Pemula",
    "focus": "Membaca not balok",
    "ready": "Sudah mengenali nama tuts.",
    "watch": "Hubungkan letak not pada paranada dengan tuts; hentikan video untuk mencoba.",
    "task": "Baca lima not pada contoh chapter tanpa melihat nama tuts.",
    "start": 0
  },
  "meter": {
    "id": "_LipFNI8Ilo",
    "title": "BELAJAR KETUKAN PADA NOT BALOK - NOT BALOK DASAR | BELAJAR PIANO INDONESIA",
    "author": "Erika Oei",
    "checked": "2026-10-06",
    "language": "Indonesia",
    "level": "Pemula",
    "focus": "Nilai not dan hitungan",
    "ready": "Kenal pulsa; sudah membuka chapter paranada.",
    "watch": "Video mengulang ketukan dasar. Gunakan contoh chapter untuk penerapan 2/4, 3/4, dan 4/4.",
    "task": "Tepuk contoh dua birama dengan not panjang dan istirahat; hitung dengan suara.",
    "start": 0
  },
  "symbols": {
    "id": "sfty1bjShBI",
    "title": "How to Play Legato & Staccato on the Piano | Technique Tuesday Tutorial",
    "author": "PianoTips",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Pemula",
    "focus": "Legato dan staccato",
    "ready": "Dapat membaca pola lima nada.",
    "watch": "Bandingkan panjang bunyi dan pelepasan tuts. Video mendampingi artikulasi, bukan seluruh aksidental.",
    "task": "Mainkan pola chapter sekali legato dan sekali staccato; jelaskan bedanya.",
    "start": 0
  },
  "together": {
    "id": "ngc0VUe-LV0",
    "title": "Piano Hand Independence For Beginners",
    "author": "Pianote",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Pemula",
    "focus": "Menyatukan dua tangan",
    "ready": "Pola lima jari nyaman dengan tangan terpisah.",
    "watch": "Mulai pola paling mudah. Ikuti titik serangan bersama pada tempo lebih lambat daripada demonstrasi.",
    "task": "Mainkan empat ketuk dengan dua tangan; tandai kapan keduanya bertemu.",
    "start": 0
  },
  "accompaniment": {
    "id": "ioZVSjQB54w",
    "title": "Left Hand Playing Made Easy - Piano Lessons (Pianote)",
    "author": "Pianote",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Pemula menuju menengah",
    "focus": "Pengiring tangan kiri",
    "ready": "Dapat memainkan melodi pendek dan bass sederhana.",
    "watch": "Pilih pola kiri paling sederhana sebelum menambahkan variasi.",
    "task": "Mainkan melodi chapter di atas bass, lalu ubah bass menjadi broken chord.",
    "start": 0
  },
  "independence": {
    "id": "ngc0VUe-LV0",
    "title": "Piano Hand Independence For Beginners",
    "author": "Pianote",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Pemula menuju menengah",
    "focus": "Koordinasi dan kemandirian tangan",
    "ready": "Sudah mencoba melodi dengan bass.",
    "watch": "Kemandirian dibangun bertahap; berhenti pada pola yang masih terkontrol.",
    "task": "Mainkan kiri terpisah dan kanan tersambung pada dua birama; ulang jika pulsa terputus.",
    "start": 0
  },
  "scales": {
    "id": "vIuzrV1dwPs",
    "title": "How To Play Any Major Scale On The Piano",
    "author": "Pianote",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Pemula lanjut",
    "focus": "Pola mayor lintas tonalitas",
    "ready": "Paham semitone dan penjarian C mayor.",
    "watch": "Pakai aturan pola untuk satu tonalitas dahulu; rujuk tabel chapter untuk penjarian spesifik.",
    "task": "Mainkan mayor C lalu G satu oktaf, sebut nada yang berubah.",
    "start": 0
  },
  "minor": {
    "id": "aClctmxVMDU",
    "title": "Learn Piano Scales: Major, Natural, Harmonic, Melodic Minor & Chromatic Scales.",
    "author": "Piano Keyboard Guide",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Pemula lanjut menuju menengah",
    "focus": "Mayor, minor, dan kromatis",
    "ready": "Tangga nada mayor satu oktaf sudah stabil.",
    "watch": "Bandingkan nada yang berubah antarjenis minor. Arpeggio dipelajari dari demonstrasi tambahan di chapter.",
    "task": "Mainkan A minor natural dan harmonis; jelaskan peran G dan G♯.",
    "start": 0,
    "extra": {
      "id": "xbYIArqfwSQ",
      "title": "Arpeggios 101 (Beginner Piano Lesson)",
      "author": "Pianote",
      "checked": "2026-10-06",
      "language": "Inggris",
      "start": 50,
      "focus": "Cara latihan arpeggio (0:50)"
    }
  },
  "movement": {
    "id": "FlmhKWXkR30",
    "title": "Piano Tutorial - Chords Jumps - Level 2B - (Lesson)",
    "author": "SuperMANgino",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah awal",
    "focus": "Perpindahan akor dengan lompatan",
    "ready": "Dapat memainkan triad tanpa ketegangan.",
    "watch": "Ambil latihan perpindahan sederhana; video ini bukan latihan oktaf cepat atau double notes lanjut.",
    "task": "Latih perpindahan C–G dengan persiapan posisi tanpa bunyi, lalu mainkan perlahan.",
    "start": 0
  },
  "chords": {
    "id": "7pa7IdX3TQo",
    "title": "Building seventh chords on the piano keyboard",
    "author": "Bill Hilton",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah awal",
    "focus": "Membangun akor tujuh",
    "ready": "Mengenal triad mayor/minor dan interval terts.",
    "watch": "Perhatikan susunan terts dan nada ketujuh; sus/add tetap memakai contoh chapter.",
    "task": "Bandingkan C, Cmaj7, dan C7; sebut nada tambahannya.",
    "start": 0
  },
  "function": {
    "id": "l5BYWY6ZJJs",
    "title": "Piano Chord Hacks #2: Inversion Basics (Piano Lesson)",
    "author": "Pianote",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah awal",
    "focus": "Inversi dan perpindahan dekat",
    "ready": "Dapat membentuk triad C, F, G.",
    "watch": "Inversi menjaga nada bersama. Video mendampingi voice leading; fungsi dan kadens dibahas dalam materi.",
    "task": "Mainkan C–F–G–C dengan inversi dekat; sebut fungsi tiap akor.",
    "start": 0
  },
  "lead": {
    "id": "5v3z0cd7okY",
    "title": "Reading Chords On a Lead Sheet - Music Theory",
    "author": "Music Matters",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah",
    "focus": "Membaca akor pada lead sheet",
    "ready": "Kenal notasi melodi dan simbol triad/akor tujuh.",
    "watch": "Pisahkan garis melodi dari simbol akor; mulai pengiring sederhana.",
    "task": "Baca melodi empat birama dengan akor di atasnya; mainkan bass akar dahulu.",
    "start": 0
  },
  "phrases": {
    "id": "eNGWFxnA_SQ",
    "title": "Piano Lesson on Chord Voicing and Melody",
    "author": "Pianist Magazine",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah",
    "focus": "Voicing melodi dan lapisan bunyi",
    "ready": "Dua tangan dan akor sudah cukup stabil.",
    "watch": "Dengarkan perbedaan melodi yang menonjol dan pengiring yang terlalu keras.",
    "task": "Rekam empat birama dengan melodi jelas dan pengiring lebih lembut.",
    "start": 0
  },
  "pedal": {
    "id": "EkE7tlmuAlc",
    "title": "Sound INSTANTLY Better (How To Use The Pedal)",
    "author": "Pianote",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah awal",
    "focus": "Pergantian pedal yang bersih",
    "ready": "Dapat memainkan dua akor tanpa pedal.",
    "watch": "Hubungkan pergantian kaki dengan perubahan harmoni; nilai kejernihan dari telinga.",
    "task": "Bandingkan C–F tanpa pedal lalu dengan pergantian pedal setelah serangan.",
    "start": 0
  },
  "interpretation": {
    "id": "iOj6dVjJsuM",
    "title": "Piano Lesson on How to Use Rubato",
    "author": "Pianist Magazine",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah menuju lanjut",
    "focus": "Rubato yang terarah",
    "ready": "Dapat memainkan frase dengan pulsa dan dinamika stabil.",
    "watch": "Jangan memakai rubato untuk menutupi kesalahan. Contoh repertoar lebih kompleks boleh didengar tanpa ditiru.",
    "task": "Mainkan frase pada pulsa tetap, lalu buat satu kelonggaran waktu yang dapat dijelaskan.",
    "start": 0
  },
  "ear": {
    "id": "U8xQfdKPRXs",
    "title": "The Ultimate Guide To Ear Training (Beginner Piano Tutorial)",
    "author": "Pianote",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Pemula lanjut menuju menengah",
    "focus": "Mendengar interval",
    "ready": "Nama nada dan interval dasar telah dikenali.",
    "watch": "Nyanyikan dua nada dan dengarkan jaraknya sebelum menjawab.",
    "task": "Tiru tiga pola pendek tanpa melihat tuts demonstrasi; cek dengan piano.",
    "start": 0
  },
  "sight": {
    "id": "qtmlozITJqc",
    "title": "Daily Piano Sight Reading Exercises (Beginner)",
    "author": "Pianote",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Pemula lanjut menuju menengah",
    "focus": "Membaca baru dengan bahan lebih mudah",
    "ready": "Dapat membaca dua kunci pada pola sederhana.",
    "watch": "Bahan beginner sengaja dipakai untuk sight-reading; jangan menghafal demonstrasi dahulu.",
    "task": "Mainkan variasi baru di website satu kali sebelum mendengarkan contoh.",
    "start": 0
  },
  "memory": {
    "id": "8kLpO6-G3UA",
    "title": "Piano Lesson on How to Memorise Using Pattern Recognition",
    "author": "Pianist Magazine",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah",
    "focus": "Memori melalui pengenalan pola",
    "ready": "Memiliki karya pendek yang telah dipelajari.",
    "watch": "Cari struktur/pola sebagai jangkar. Contoh kompleks adalah ilustrasi, bukan tugas wajib.",
    "task": "Tandai tiga jangkar dalam karya dan mulai dari masing-masing tanpa awalan.",
    "start": 0
  },
  "diagnose": {
    "id": "UU4reM8QdE0",
    "title": "The Fastest Way to Make Piano Practice Stick (Backed by Science)",
    "author": "Piano with Rebecca Bogart",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah",
    "focus": "Latihan yang lebih terarah",
    "ready": "Memiliki satu karya dan satu bagian yang belum stabil.",
    "watch": "Ubah satu masalah menjadi sasaran kecil; bandingkan hasil setelah latihan.",
    "task": "Tulis masalah nada, ritme, atau transisi; uji satu cara memperbaikinya selama lima menit.",
    "start": 0
  },
  "methods": {
    "id": "6pgaqARMhc0",
    "title": "Piano Lesson on the 20-minute Practice Session",
    "author": "Pianist Magazine",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah",
    "focus": "Sesi latihan singkat dan terfokus",
    "ready": "Dapat mengisolasi bagian sulit sebuah karya.",
    "watch": "Ambil gagasan latihan bertujuan; langkah overlap/backward chaining tetap mengikuti chapter.",
    "task": "Latih dua potongan dengan satu ketuk overlap, lalu uji sambungan tanpa berhenti.",
    "start": 0
  },
  "program": {
    "id": "6pgaqARMhc0",
    "title": "Piano Lesson on the 20-minute Practice Session",
    "author": "Pianist Magazine",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah",
    "focus": "Merencanakan latihan untuk program",
    "ready": "Memiliki karya lama dan karya baru yang bisa dibandingkan.",
    "watch": "Bedakan memperbaiki potongan dari memainkan karya utuh. Video ini membahas latihan, bukan seluruh teknik panggung.",
    "task": "Susun sesi 20 menit; rekam karya utuh sesudahnya dan catat satu fokus berikutnya.",
    "start": 0
  },
  "styles": {
    "id": "FrA7cGX-zLM",
    "title": "Baroque Keyboard Music: Basics of the Style",
    "author": "pianoTV",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah menuju lanjut",
    "focus": "Gaya keyboard Barok",
    "ready": "Dapat mendengar artikulasi dan garis melodi.",
    "watch": "Fokus karakter Barok; video tidak merangkum semua era. Bandingkan dengan uraian Klasik/Romantik dalam chapter.",
    "task": "Bandingkan dua cara artikulasi pada satu frase dan jelaskan pilihan gaya.",
    "start": 0
  },
  "polyphony": {
    "id": "pU5HH4ecEM8",
    "title": "Bach Invention 1 | Classical Piano Lesson | Early Advanced",
    "author": "Liberty Park Music",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Lanjut awal · klasik",
    "focus": "Dua suara pada Bach Invention 1",
    "ready": "Koordinasi tangan, membaca dua kunci, dan frase sudah dikuasai.",
    "watch": "Pelajari satu masuk motif dahulu; jangan mengejar tempo penampilan atau seluruh karya sekaligus.",
    "task": "Mainkan masing-masing suara pendek, lalu satukan dan pertahankan kejelasan keduanya.",
    "start": 0
  },
  "recital": {
    "id": "8kLpO6-G3UA",
    "title": "Piano Lesson on How to Memorise Using Pattern Recognition",
    "author": "Pianist Magazine",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Lanjut · klasik",
    "focus": "Memori analitis untuk kesiapan repertoar",
    "ready": "Karya utuh dan peta bentuk sudah tersedia.",
    "watch": "Gunakan pengenalan pola sebagai persiapan resital; ensemble dan panggung tetap memerlukan praktik nyata.",
    "task": "Simulasikan karya utuh, mulai dari lima jangkar, lalu minta umpan balik pengajar.",
    "start": 0
  },
  "groove": {
    "id": "HjycAkgI9X0",
    "title": "POPULAR PIANO ACCOMPANIMENT RHYTHM PATTERNS - How I Make Them Sound Fuller",
    "author": "Bitesize Piano",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah · pop",
    "focus": "Pola ritme pengiring pop",
    "ready": "Lead sheet dan perpindahan akor sederhana stabil.",
    "watch": "Pilih satu pola sebelum mempertebal bunyi; pertahankan ruang untuk melodi/vokal.",
    "task": "Terapkan satu pola pengiring pada C–G–Am–F selama delapan birama.",
    "start": 0
  },
  "arrange": {
    "id": "sP7IaJ4E52U",
    "title": "Simple Piano Accompaniment Patterns Tutorial",
    "author": "jmagemusic",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah menuju lanjut · pop",
    "focus": "Variasi pengiring untuk aransemen",
    "ready": "Melodi dan bass dapat dimainkan bersama.",
    "watch": "Awali pola sederhana; contoh stride di akhir opsional setelah pola awal nyaman.",
    "task": "Buat dua versi pengiring pada melodi orisinal, kemudian tambah intro dua birama.",
    "start": 0
  },
  "reharmonize": {
    "id": "yHidck4o3JE",
    "title": "The Reharmonization Game 🎹 Play Any Note With Any Chord",
    "author": "Piano With Jonny",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Lanjut · pop/jazz",
    "focus": "Reharmonisasi berdasarkan bunyi dan fungsi",
    "ready": "Paham akor tujuh, inversi, dan dominan sekunder.",
    "watch": "Materi modern jazz lebih kompleks: pilih satu substitusi, bukan meniru semua warna sekaligus.",
    "task": "Uji C dan Am di bawah nada E; bandingkan fungsi dan buat satu substitusi tambahan.",
    "start": 0
  },
  "blues": {
    "id": "jKhsacA76KU",
    "title": "Blues Piano 101 (Beginner Piano Lesson)",
    "author": "Pianote",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah · awal jalur jazz",
    "focus": "Dasar blues dan bentuk 12-bar",
    "ready": "Triad/akor dominan tujuh dan pulsa sudah dikenal.",
    "watch": "Materi beginner merujuk pemula blues, bukan pemula piano absolut. Hitung bentuk sebelum improvisasi.",
    "task": "Mainkan satu chorus blues dengan bass akar dan motif tiga nada.",
    "start": 0
  },
  "voicings": {
    "id": "_ldxtscmCpo",
    "title": "Shell Voicings Explained Clearly (Beginner Jazz Piano)",
    "author": "Jazz Tutorial",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Menengah menuju lanjut · jazz",
    "focus": "Shell voicings sebagai fondasi",
    "ready": "Paham terts/ketujuh dan ii–V–I.",
    "watch": "Mulai shells sebelum rootless/extensions; bagian lanjut tetap mengikuti materi dan evaluasi.",
    "task": "Mainkan Dm7–G7–Cmaj7 dengan guide tones; pindahkan ke F.",
    "start": 0
  },
  "improv": {
    "id": "EFaDsmw_ycQ",
    "title": "Improvisation with Jesus Molina (Piano Lesson + PDF included)",
    "author": "Pianote",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Lanjut · jazz",
    "focus": "Improvisasi dan pengembangan ide",
    "ready": "Bentuk, blues/ii–V–I, dan guide tones stabil.",
    "watch": "Dengarkan pilihan ritme dan arah kalimat. Demonstrasi virtuoso bukan target kecepatan.",
    "task": "Improvisasikan dua chorus dengan satu motif, ruang diam, dan target chord tones.",
    "start": 0
  },
  "individual": {
    "id": "n0plki8p1rU",
    "title": "How to do 3 Against 2 Polyrhythm",
    "author": "Ashlee Young Piano Studio",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Lanjut",
    "focus": "Poliritme 3:2 sebagai masalah spesifik",
    "ready": "Koordinasi dan subdivisi dasar stabil; tangan bisa memainkan pola berbeda.",
    "watch": "Gunakan enam subdivisi untuk memetakan dua ritme. Ini satu fokus teknik, bukan seluruh teknik expert.",
    "task": "Tepuk 3:2, pindahkan ke dua nada piano, lalu tunjukkan hasil pada pengajar.",
    "start": 0
  },
  "independent": {
    "id": "8kLpO6-G3UA",
    "title": "Piano Lesson on How to Memorise Using Pattern Recognition",
    "author": "Pianist Magazine",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Lanjut",
    "focus": "Analisis pola untuk memori mandiri",
    "ready": "Memiliki karya lanjut dan dapat menjelaskan bentuk/harmoninya.",
    "watch": "Terapkan metode pada karya sendiri; komposisi/ensemble tetap membutuhkan proyek terpisah.",
    "task": "Buat peta motif dan lima jangkar; uji dua metode latihan serta tulis perbandingannya.",
    "start": 0
  },
  "portfolio": {
    "id": "6pgaqARMhc0",
    "title": "Piano Lesson on the 20-minute Practice Session",
    "author": "Pianist Magazine",
    "checked": "2026-10-06",
    "language": "Inggris",
    "level": "Lanjut",
    "focus": "Merancang siklus latihan untuk portofolio",
    "ready": "Memiliki program utuh serta umpan balik manusia sebelumnya.",
    "watch": "Video pendamping strategi latihan, bukan sertifikasi atau pengganti evaluasi penampilan.",
    "task": "Rencanakan tiga rekaman hari berbeda; kumpulkan refleksi dan umpan balik pengajar.",
    "start": 0
  }
};
