import {exercises,exerciseFor,noteName,noteDrill,matchNotes,parseMidi,weeklySummary} from './exercises.js';
export function playerPanel(stage=1,chapter=0,lesson=false,exerciseId){const chosen=exercises.find(e=>e.id===exerciseId)||exerciseFor(stage,chapter);return `<section class="panel ${lesson?'':'wide'}" id="practice-player"><span class="eyebrow">DENGARKAN & LATIH POTONGAN</span><h3>${lesson?'Contoh chapter':'Latihan bagian sulit'}</h3><label>Contoh<select id="exercise-select">${exercises.map(e=>`<option value="${e.id}" ${e===chosen?'selected':''}>${e.group||`${e.stage}.${e.chapter+1}`} · ${e.title}</option>`).join('')}</select></label><p id="exercise-caption" class="muted">${chosen.title}</p><div class="tool-controls"><label>Dari langkah<select id="loop-from"></select></label><label>Sampai langkah<select id="loop-to"></select></label><label>Tempo awal<input id="loop-bpm" type="number" min="30" max="200" value="60"></label><label>Target BPM<input id="loop-target" type="number" min="30" max="200" value="90"></label><label>Tambah tiap putaran<input id="loop-step" type="number" min="0" max="20" value="5"></label><label>Putaran<input id="loop-count" type="number" min="1" max="20" value="3"></label></div><div class="actions"><button id="loop-play">Putar & ulangi ♬</button><button id="loop-stop" class="outline" disabled>Hentikan contoh</button></div><p class="status-line" style="margin-top:12px">Tempo bertambah setelah satu putaran contoh selesai, bukan setelah permainanmu dinilai. Pilih tambah 0 untuk tempo tetap.</p><p id="loop-status" role="status">Pilih potongan, lalu dengarkan.</p><div class="follow-notes" id="follow-notes"></div><p id="follow-now" class="note-display" role="status">—</p><p class="status-line">Tuts panduan menyala mengikuti contoh. Kamu bisa ikut memainkan piano pada halaman ini.</p></section>`;}
export function studioLearning(){return `${playerPanel()}<section class="panel wide"><span class="eyebrow">JAWAB DENGAN MEMAINKAN NADA</span><h3>Tantangan keyboard</h3><p>Mainkan nada yang diminta pada keyboard virtual, keyboard komputer, atau piano MIDI. Nada yang salah diberi koreksi; lepaskan tuts sebelum mencoba lagi.</p><div class="tool-controls"><label>Mode<select id="drill-mode"><option value="sequence">Urutan C–E–G–F–D–C</option><option value="random">8 nada acak</option><option value="chord">Akor: C, F, G, Am</option></select></label><button id="drill-start">Mulai tantangan</button><button id="drill-stop" class="outline">Akhiri</button></div><p id="drill-target" class="note-display">Siap mencoba?</p><p id="drill-feedback" role="status">Akor dinilai sebagai kumpulan nada; mainkan atau tahan nada-nadanya bersamaan.</p><button id="drill-save" disabled>Simpan hasil latihan</button><p class="status-line">Hasil tersimpan sebagai catatan jurnal setelah login; tidak otomatis menggantikan ujian praktik.</p></section>`;}
export function weeklyPanel(progress,logged){const w=weeklySummary(progress);return `<section class="panel weekly-panel"><span class="eyebrow">FOKUS MINGGU INI · MULAI ${w.start}</span><h3>${logged?'Target pribadimu':'Contoh rencana belajar'}</h3><p>${w.focus}</p><div class="actions"><a href="${w.href||`#stage/${w.stage}/${w.chapter}`}">Ke tugas berikutnya →</a><a href="#studio">Latih di studio →</a></div>${logged?`<div class="weekly-stats"><span><strong>${w.sessions}/${w.goal.sessions}</strong> sesi</span><span><strong>${w.minutes}/${w.goal.minutes}</strong> menit</span></div><div class="progress-track"><span style="width:${Math.min(100,w.minutes/w.goal.minutes*100)}%"></span></div><form id="weekly-form"><div class="tool-controls"><label>Target sesi<input name="sessions" type="number" min="1" max="7" value="${w.goal.sessions}" required></label><label>Target menit<input name="minutes" type="number" min="10" max="1000" value="${w.goal.minutes}" required></label><button type="submit">Simpan target</button></div></form>`:'<p class="status-line" style="margin-top:16px">Masuk untuk target dan rekomendasi berdasarkan progresmu. Semua alat latihan tetap terbuka.</p>'}</section>`;}
export function bindWeekly(save,refresh){const form=document.querySelector('#weekly-form');if(form)form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form);if(await save('weekly',{weekly:{sessions:Number(f.get('sessions')),minutes:Number(f.get('minutes'))}}))refresh();};}
const $=s=>document.querySelector(s);
export function bindPlayer(adapter){if(!$('#practice-player'))return ()=>{};let disposed=false,generation=0,timers=[],voices=[],round=0,frame;const cleanup=()=>{generation++;cancelAnimationFrame(frame);timers.forEach(clearTimeout);timers=[];voices.forEach(v=>adapter.releaseTone(v));voices=[];document.querySelectorAll('.follow-key').forEach(k=>k.classList.remove('on'));document.querySelectorAll('.key.example-on').forEach(k=>k.classList.remove('example-on'));if($('#loop-stop'))$('#loop-stop').disabled=true;if($('#loop-play'))$('#loop-play').disabled=false;};
function options(){cleanup();const e=exercises[Number($('#exercise-select').value)];$('#exercise-caption').textContent=e.title;$('#loop-from').innerHTML=e.events.map((x,i)=>`<option value="${i}">${i+1} · ${x.notes.map(noteName).join('+')||'diam'}</option>`).join('');$('#loop-to').innerHTML=$('#loop-from').innerHTML;$('#loop-to').value=String(e.events.length-1);$('#follow-notes').innerHTML=Array.from({length:49},(_,i)=>i+36).map(n=>`<span class="follow-key ${[1,3,6,8,10].includes(n%12)?'black':''}" data-follow="${n}">${noteName(n)}</span>`).join('');$('#loop-status').textContent='Pilih potongan, lalu dengarkan.';$('#follow-now').textContent='—';}
$('#exercise-select').onchange=options;options();$('#loop-stop').onclick=()=>{cleanup();$('#loop-status').textContent='Contoh dihentikan.';};
$('#loop-play').onclick=async()=>{cleanup();const from=Number($('#loop-from').value),to=Number($('#loop-to').value),bpm=Number($('#loop-bpm').value),target=Number($('#loop-target').value),increase=Number($('#loop-step').value),count=Number($('#loop-count').value);if(from>to||![bpm,target].every(n=>Number.isFinite(n)&&n>=30&&n<=200)||!Number.isInteger(count)||count<1||count>20||!Number.isFinite(increase)||increase<0||increase>20){$('#loop-status').textContent='Periksa potongan dan tempo (30–200 BPM), putaran 1–20, tambah 0–20.';return;}const e=exercises[Number($('#exercise-select').value)],segment=e.events.slice(from,to+1),offset=segment[0].beat;const session=generation,ctx=await adapter.sound();if(!ctx||disposed||session!==generation)return;$('#loop-play').disabled=true;$('#loop-stop').disabled=false;round=0;
function playRound(){if(disposed||session!==generation)return;voices=[];round++;const tempo=Math.min(Math.max(bpm,target),bpm+(round-1)*increase),step=60/tempo,start=ctx.currentTime+.08;$('#loop-status').textContent=`Putaran ${round}/${count} · ${tempo} BPM · langkah ${from+1}–${to+1}`;for(const event of segment){const at=start+(event.beat-offset)*step;const soundVoices=event.notes.map(n=>adapter.startTone(ctx,n,at,event.velocity));soundVoices.forEach(v=>adapter.releaseTone(v,at+event.duration*(event.gate??.88)*step));voices.push(...soundVoices);}cancelAnimationFrame(frame);function paint(){if(disposed||session!==generation)return;const beat=offset+(ctx.currentTime-start)/step,sounding=[...new Set(segment.filter(x=>x.beat<=beat&&x.beat+x.duration*(x.gate??.88)>beat).flatMap(x=>x.notes))];document.querySelectorAll('.follow-key').forEach(k=>k.classList.toggle('on',sounding.includes(Number(k.dataset.follow))));document.querySelectorAll('.key').forEach(k=>k.classList.toggle('example-on',sounding.includes(Number(k.dataset.note))));$('#follow-now').textContent=sounding.map(noteName).join(' + ')||'Istirahat';frame=requestAnimationFrame(paint);}paint();const end=Math.max(...segment.map(x=>x.beat-offset+x.duration))*step;timers.push(setTimeout(()=>{if(disposed||session!==generation)return;if(round<count)playRound();else {cleanup();$('#loop-status').textContent=`Selesai ${count} putaran. Coba mainkan potongannya sendiri.`;}},(end+.1)*1000));}playRound();};
return ()=>{disposed=true;cleanup();};}
export function bindLearning(adapter){let disposed=false,drill=null,index=0,attempts=0,correct=0,keysDown=new Set(),ready=true,result=null,startedAt=0;
function target(){if(!drill)return;$('#drill-target').textContent=`${index+1}/${drill.length} · ${drill[index].notes.map(noteName).join(' + ')}`;}
function input(note,on){if(on)keysDown.add(note);else keysDown.delete(note);if(!drill)return;if(!on){if(!keysDown.size)ready=true;return;}if(!ready)return;const expected=drill[index].notes;if(expected.length>1&&keysDown.size<expected.length&&[...keysDown].every(n=>expected.includes(n)))return;attempts++;ready=false;const ok=matchNotes([...keysDown],expected);if(ok){correct++;index++;$('#drill-feedback').textContent='✓ Tepat. Lepaskan tuts, lalu lanjut.';if(index===drill.length){result={score:Math.round(correct/attempts*100),mode:$('#drill-mode').value};$('#drill-target').textContent=`Selesai · ${result.score}% · ${attempts} percobaan`;$('#drill-save').disabled=false;drill=null;}else target();}else $('#drill-feedback').textContent=`Belum tepat. Diminta ${expected.map(noteName).join(' + ')}, dimainkan ${[...keysDown].map(noteName).join(' + ')}. Lepaskan semua tuts lalu coba lagi.`;}
adapter.setInputListener(input);
$('#drill-start').onclick=()=>{drill=noteDrill($('#drill-mode').value);startedAt=Date.now();index=0;attempts=0;correct=0;keysDown.clear();ready=true;result=null;$('#drill-save').disabled=true;target();$('#drill-feedback').textContent='Mainkan nada pertama. Jawaban diperiksa otomatis.';};$('#drill-stop').onclick=()=>{drill=null;keysDown.clear();$('#drill-target').textContent='Tantangan dihentikan.';$('#drill-save').disabled=true;};$('#drill-save').onclick=async()=>{if(!result)return;const seconds=Math.max(1,Math.round((Date.now()-startedAt)/1000));if(await adapter.save('journal',{entry:{stage:1,minutes:Math.min(480,Math.max(1,Math.ceil(seconds/60))),tempo:60,note:`Latihan keyboard ${result.mode}: ${result.score}% (${correct} benar / ${attempts} percobaan), ${seconds} detik. Durasi jurnal dibulatkan ke menit.`}})){$('#drill-save').disabled=true;}};
return ()=>{disposed=true;adapter.setInputListener(null);};}


export function createMidi(adapter){let midi=null,midiInputs=[],midiNotes=new Set(),monitor=true,selection="";
const host=document.createElement("section");host.className="usb-midi-settings";host.innerHTML='<section class="panel wide"><span class="eyebrow">PIANO DIGITAL SEBAGAI INPUT</span><h3>Hubungkan keyboard MIDI</h3><p>Hubungkan port USB-to-host piano ke PC dengan kabel data, buka Chrome/Edge, lalu tekan Hubungkan MIDI dan izinkan akses. Pilih nama pianomu di daftar Perangkat. Nada, kekuatan tekan, dan pedal sustain akan mengikuti instrumen.</p><div class="tool-controls"><button id="midi-connect">Hubungkan MIDI</button><label>Perangkat<select id="midi-device"><option value="">Belum terhubung</option></select></label><button class="outline" id="midi-disconnect">Putuskan</button><label><input type="checkbox" id="midi-monitor" checked> Bunyi dari website</label></div><p id="midi-status" role="status">Gunakan browser yang mendukung Web MIDI, seperti Chrome atau Edge, melalui HTTPS. Koneksi tetap aktif saat pindah chapter dalam tab ini. Jika nada terdengar dua kali, matikan Bunyi dari website atau Local Control di piano. Jika perangkat tidak muncul, periksa kabel data dan driver dari produsen; port USB flashdisk tidak mengirim MIDI.</p></section>';document.querySelector("#main").after(host);const status=$("#midi-status");
function offAll(){for(const n of midiNotes)adapter.noteOff(n);midiNotes.clear();adapter.pedal(false);}
function detach(){midiInputs.forEach(i=>i.onmidimessage=null);midiInputs=[];offAll();}
function message(e){const m=parseMidi(e.data);if(!m)return;if(m.type==='on'){midiNotes.add(m.note);adapter.noteOn(m.note,m.velocity,monitor);}else if(m.type==='off'){midiNotes.delete(m.note);adapter.noteOff(m.note);}else adapter.pedal(m.down);status.textContent=m.type==='pedal'?`Pedal ${m.down?'aktif':'lepas'}`:`MIDI: ${noteName(m.note)} ${m.type==='on'?`· velocity ${m.velocity}`:'dilepas'}`;}
function devices(){if(!midi)return;const ports=[...midi.inputs.values()].filter(i=>i.state!=='disconnected');const select=$('#midi-device');select.innerHTML='';for(const port of ports){const option=document.createElement('option');option.value=port.id;option.textContent=port.name||'Keyboard MIDI';select.append(option);}if(!ports.length){detach();const option=document.createElement('option');option.value='';option.textContent='Tidak ada perangkat';select.append(option);status.textContent='Izin diberikan, tetapi belum ada keyboard MIDI. Sambungkan perangkat; daftar diperbarui otomatis.';return;}if(ports.some(p=>p.id===selection))select.value=selection;selection=select.value;const selected=ports.find(p=>p.id===selection);if(midiInputs[0]!==selected)detach();selected.onmidimessage=message;midiInputs=[selected];status.textContent=`Terhubung: ${selected.name||'Keyboard MIDI'}. Mainkan nada untuk mencoba.`;}
$('#midi-connect').onclick=async()=>{if(!navigator.requestMIDIAccess){status.textContent='Web MIDI tidak tersedia di browser ini. Coba Chrome atau Edge; keyboard virtual tetap bisa digunakan.';return;}try{await adapter.sound();const access=await navigator.requestMIDIAccess({sysex:false});midi=access;midi.onstatechange=devices;devices();}catch(e){status.textContent=e.name==='NotAllowedError'?'Izin MIDI ditolak. Izinkan akses melalui pengaturan browser lalu coba lagi.':'MIDI belum bisa dihubungkan. Periksa perangkat dan izin browser.';}};$('#midi-device').onchange=e=>{selection=e.target.value;devices();};$('#midi-monitor').onchange=e=>monitor=e.target.checked;$('#midi-disconnect').onclick=()=>{detach();if(midi)midi.onstatechange=null;midi=null;$('#midi-device').innerHTML='<option value="">Belum terhubung</option>';status.textContent='MIDI diputuskan.';};
return {refresh:()=>{if($("#sustain"))$("#sustain").checked=adapter.sustained();}};
}
