// Standard MIDI Files 0/1: https://midi.org/standard-midi-files-specification
export function readMidi(buffer){
  const bytes=new Uint8Array(buffer),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let p=0,limit=bytes.length,total=0;
  const need=n=>{if(p+n>limit)throw Error('File MIDI terpotong atau rusak.');};
  const u8=()=>{need(1);return bytes[p++];},u16=()=>{need(2);const n=view.getUint16(p);p+=2;return n;},u32=()=>{need(4);const n=view.getUint32(p);p+=4;return n;};
  const text=n=>{need(n);const s=new TextDecoder().decode(bytes.subarray(p,p+n));p+=n;return s;};
  const vlq=()=>{let n=0;for(let i=0;i<4;i++){const b=u8();n=n*128+(b&127);if(!(b&128))return n;}throw Error('Delta MIDI tidak valid.');};
  if(bytes.length>5*1024*1024)throw Error('Batas file MIDI 5 MB.');
  if(text(4)!=='MThd')throw Error('Pilih file Standard MIDI (.mid atau .midi).');
  const header=u32(),headerEnd=p+header;if(header<6||headerEnd>limit)throw Error('Header MIDI tidak valid.');
  const format=u16(),count=u16(),division=u16();if(format>1||!count||count>256||(format===0&&count!==1)||!division)throw Error('Gunakan MIDI format 0 atau 1 dengan maksimal 256 track.');p=headerEnd;
  let fixed=0;if(division&0x8000){const fps=256-(division>>8),sub=division&255;if(![24,25,29,30].includes(fps)||!sub)throw Error('Waktu SMPTE tidak valid.');fixed=1/((fps===29?29.97:fps)*sub);}
  const tracks=[],events=[];
  for(let track=0;track<count;track++){
    limit=bytes.length;if(text(4)!=='MTrk')throw Error('Track MIDI tidak valid.');const length=u32();limit=p+length;if(limit>bytes.length)throw Error('Track MIDI terpotong.');
    let tick=0,running=0,name=`Track ${track+1}`;
    while(p<limit){if(++total>100000)throw Error('MIDI terlalu kompleks (maksimal 100.000 event).');tick+=vlq();let status=u8();if(status<128){if(!running)throw Error('Running status MIDI tidak valid.');p--;status=running;}
      if(status===255){running=0;const type=u8(),size=vlq();need(size);if(type===81){if(size!==3)throw Error('Tempo MIDI tidak valid.');const tempo=bytes[p]*65536+bytes[p+1]*256+bytes[p+2];if(!tempo)throw Error('Tempo MIDI nol.');events.push({tick,type:'tempo',tempo,track});}if(type===3)name=new TextDecoder().decode(bytes.subarray(p,p+size)).slice(0,100);p+=size;if(type===47){if(size!==0)throw Error('Akhir track tidak valid.');p=limit;}}
      else if(status===240||status===247){running=0;const size=vlq();need(size);p+=size;}
      else if(status>=128&&status<=239){running=status;const type=status>>4,channel=status&15,a=u8(),b=type===12||type===13?0:u8();if(a>127||b>127)throw Error('Data MIDI tidak valid.');if(type===9&&b>0)events.push({tick,type:'on',note:a,velocity:b,channel,track});else if(type===8||type===9)events.push({tick,type:'off',note:a,channel,track});else if(type===11&&[64,120,121,123].includes(a))events.push({tick,type:'cc',control:a,value:b,channel,track});}
      else throw Error('Status MIDI tidak didukung.');
    }tracks.push({id:track,name,endTick:tick});
  }
  events.sort((a,b)=>a.tick-b.tick||a.track-b.track);let tick=0,time=0,tempo=500000;
  for(const event of events){time+=(event.tick-tick)*(fixed||tempo/1000000/division);tick=event.tick;event.time=time;if(event.type==='tempo')tempo=event.tempo;}
  const finalTick=Math.max(...tracks.map(t=>t.endTick)),end=time+(finalTick-tick)*(fixed||tempo/1000000/division),notes=[],active=new Map(),pedals=new Set(),pending=new Map();
  const close=(n,t)=>{n.duration=Math.max(.01,t-n.time);notes.push(n);};
  for(const e of events){if(e.type==='tempo'||e.channel===9)continue;const channel=String(e.channel),key=`${channel}:${e.note}`;
    if(e.type==='on'){const queue=active.get(key)||[];queue.push({note:e.note,velocity:e.velocity,time:e.time,track:e.track,channel:e.channel});active.set(key,queue);}
    else if(e.type==='off'){const queue=active.get(key);if(!queue?.length)continue;const n=queue.shift();if(pedals.has(channel)){const held=pending.get(channel)||[];held.push(n);pending.set(channel,held);}else close(n,e.time);}
    else if(e.type==='cc'){const release=()=>{for(const n of pending.get(channel)||[])close(n,e.time);pending.delete(channel);};if(e.control===64){if(e.value>=64)pedals.add(channel);else{pedals.delete(channel);release();}}else{pedals.delete(channel);release();if(e.control!==121)for(const [k,queue] of active)if(k.startsWith(channel+':')){queue.forEach(n=>close(n,e.time));active.delete(k);}}}
  }
  for(const queue of [...active.values(),...pending.values()])queue.forEach(n=>close(n,end));
  notes.sort((a,b)=>a.time-b.time);if(!notes.length)throw Error('Tidak ada nada melodis di file ini (track drum dilewati).');if(notes.length>20000||end>3600)throw Error('Batas MIDI: 20.000 nada dan durasi 60 menit.');
  return {format,tracks:tracks.map(t=>({...t,notes:notes.filter(n=>n.track===t.id).length})),notes,duration:Math.max(end,...notes.map(n=>n.time+n.duration)),outside:notes.filter(n=>n.note<21||n.note>108).length};
}

export function midiFilePanel(){return `<section class="panel wide" id="midi-file-panel"><span class="eyebrow">LAGU DARI FILE MIDI</span><h3>Putar dan ikuti lagunya</h3><p>Buka file .mid/.midi dari perangkatmu. File tetap lokal; nada melodis dimainkan dengan suara grand piano, track drum dilewati.</p><label>File MIDI<input id="midi-file" type="file" accept=".mid,.midi,audio/midi,audio/x-midi"></label><div class="tool-controls"><label>Track<select id="song-track" disabled><option value="all">Semua track melodis</option></select></label><label>Kecepatan<select id="song-speed"><option value="0.5">50%</option><option value="0.75">75%</option><option value="1" selected>100%</option><option value="1.25">125%</option><option value="1.5">150%</option></select></label><label><input id="song-loop" type="checkbox"> Ulang lagu</label><label><input id="song-follow" type="checkbox" checked> Ikuti tuts</label></div><div class="actions"><button id="song-play" disabled>Putar MIDI ♬</button><button id="song-pause" class="outline" disabled>Jeda</button><button id="song-stop" class="outline" disabled>Stop & ulang dari awal</button><button id="song-keyboard" class="outline">Ke piano ↑</button></div><label>Posisi lagu<input id="song-seek" type="range" min="0" max="1" step="0.01" value="0" disabled></label><p id="song-time" role="timer">0:00 / 0:00</p><p id="song-status" role="status">Belum ada file. MIDI format 0/1, maksimal 5 MB.</p><p class="status-line">Tuts berwarna oranye mengikuti lagu; tuts hijau adalah permainanmu. Pilih 88 tuts untuk melihat rentang penuh. Perubahan instrumen dan pitch bend tidak diterapkan. <a href="https://midi.org/standard-midi-files-specification" target="_blank" rel="noopener">Format MIDI</a></p></section>`;}

export function bindMidiFile(adapter){
  const $=s=>document.querySelector(s);let song=null,selected=[],position=0,speed=1,playing=false,disposed=false,generation=0,loadId=0,ctx,origin=0,index=0,timer,frame,voices=[],lastFollow=-1;
  const clock=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
  const now=()=>playing?Math.max(0,Math.min(song.duration,position+(ctx.currentTime-origin)*speed)):position;
  function display(){const t=now();$('#song-seek').value=String(t);$('#song-time').textContent=`${clock(t)} / ${clock(song?.duration||0)}`;}
  function clear(){generation++;clearInterval(timer);cancelAnimationFrame(frame);voices.forEach(v=>adapter.releaseTone(v.voice));voices=[];document.querySelectorAll('.key.song-on').forEach(k=>k.classList.remove('song-on'));}
  function pause(){if(playing)position=now();playing=false;clear();if(!disposed){$('#song-play').disabled=!song;$('#song-pause').disabled=true;display();}}
  function paint(){if(!playing||disposed)return;const t=now(),sounding=selected.filter(n=>n.time<=t&&n.time+n.duration>t).map(n=>n.note);document.querySelectorAll('.key').forEach(k=>k.classList.toggle('song-on',sounding.includes(Number(k.dataset.note))));if($('#song-follow').checked&&sounding.length&&sounding[0]!==lastFollow){lastFollow=sounding[0];adapter.follow(sounding[0]);}display();if(t>=song.duration){pause();if($('#song-loop').checked){position=0;play();}else $('#song-status').textContent='Lagu selesai. Coba ulang pada tempo lebih pelan.';return;}frame=requestAnimationFrame(paint);}
  function schedule(){if(!playing)return;const t=now();voices=voices.filter(v=>v.end>ctx.currentTime);while(index<selected.length&&selected[index].time<=t+.12*speed){const n=selected[index++],end=origin+(n.time+n.duration-position)/speed;if(end<=ctx.currentTime)continue;const at=Math.max(ctx.currentTime+.005,origin+(n.time-position)/speed),voice=adapter.startTone(ctx,n.note,at,n.velocity);adapter.releaseTone(voice,end);voices.push({voice,end:end+.36});}}
  async function play(){if(!song||playing||disposed)return;clear();const session=generation;ctx=await adapter.sound();if(!ctx||disposed||session!==generation)return;if(position>=song.duration)position=0;origin=ctx.currentTime+.05;index=selected.findIndex(n=>n.time+n.duration>position);if(index<0)index=selected.length;playing=true;lastFollow=-1;$('#song-play').disabled=true;$('#song-pause').disabled=false;$('#song-stop').disabled=false;$('#song-status').textContent='Memainkan MIDI. Kamu bisa bermain bersama di piano.';schedule();timer=setInterval(schedule,25);paint();}
  $('#midi-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;pause();const request=++loadId;try{if(file.size>5*1024*1024)throw Error('Batas file MIDI 5 MB.');const parsed=readMidi(await file.arrayBuffer());if(disposed||request!==loadId)return;song=parsed;selected=song.notes;position=0;const select=$('#song-track');select.innerHTML='<option value="all">Semua track melodis</option>';for(const t of song.tracks.filter(t=>t.notes)){const option=document.createElement('option');option.value=t.id;option.textContent=`${t.name} · ${t.notes} nada`;select.append(option);}select.disabled=false;$('#song-seek').max=String(song.duration);$('#song-seek').disabled=false;$('#song-play').disabled=false;$('#song-stop').disabled=false;$('#song-status').textContent=`${file.name} · ${song.notes.length} nada · ${song.tracks.length} track${song.outside?` · ${song.outside} nada di luar 88 tuts tetap berbunyi`:''}`;display();}catch(error){if(disposed||request!==loadId)return;song=null;selected=[];position=0;$('#song-play').disabled=$('#song-stop').disabled=$('#song-seek').disabled=$('#song-track').disabled=true;$('#song-status').textContent=error.message;display();}e.target.value='';};
  $('#song-play').onclick=play;$('#song-pause').onclick=()=>{pause();$('#song-status').textContent='Dijeda. Putar untuk melanjutkan.';};$('#song-stop').onclick=()=>{pause();position=0;display();$('#song-status').textContent='Dihentikan. Posisi kembali ke awal.';};
  $('#song-speed').onchange=()=>{const resume=playing;pause();speed=Number($('#song-speed').value);if(resume)play();};$('#song-seek').oninput=()=>{const t=Number($('#song-seek').value),resume=playing;pause();position=t;display();if(resume)play();};$('#song-track').onchange=()=>{const resume=playing;pause();selected=song.notes.filter(n=>$('#song-track').value==='all'||n.track===Number($('#song-track').value));if(resume)play();};$('#song-keyboard').onclick=()=>$('#keyboard').scrollIntoView({block:'center',behavior:'smooth'});
  return ()=>{disposed=true;loadId++;pause();};
}
