import {songRecommendations,beginnerSongs,songPlacementNote} from './song-recommendations.js';
import {scoreSvg,name} from './curriculum-practice.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function songPanel(block,{interactive=true}={}){
 const songs=songRecommendations[block.id]||[];
 return `<section class="panel song-panel" id="songs-for-${block.id}"><span class="eyebrow">LAGU UNTUK LEVEL INI</span><h3>Pilih lagu yang ingin kamu mainkan.</h3><p>${esc(songPlacementNote)}</p><ol class="song-list">${songs.map((s,i)=>{
 const playable=beginnerSongs.find(p=>p.key===s.playKey);
 return `<li><h4>${esc(s.title)}</h4><p class="status-line">${esc(s.composer)} · ${i===0?'Pilihan mulai':'Pilihan berikutnya'}</p><p><strong>Versi yang dipakai:</strong> ${esc(s.version)}</p><p><strong>Tujuan:</strong> ${esc(s.focus)}</p><details><summary>Kesiapan, bagian sulit, dan rencana latihan</summary><p><strong>Siap mulai jika:</strong> ${esc(s.ready)}</p><p><strong>Perhatikan:</strong> ${esc(s.difficult)}</p><p>Latih 1–2 birama dari bagian sulit dengan satu ketuk sebelum/sesudahnya. Tepuk ritme, tentukan penjarian yang nyaman, lalu coba tangan terpisah dan gabungkan dengan overlap. Mulai sekitar 40–60 BPM atau lebih lambat; tambah tempo hanya ketika pulsa, bunyi, dan gerak stabil. Penjarian versi partitur yang dipilih lebih relevan daripada satu pola universal.</p><p><strong>Tugas:</strong> mainkan versi yang disebut sampai akhir, rekam, lalu gunakan rubrik tahap untuk nada, ritme, koordinasi, keseimbangan, artikulasi/pedal, frase, dan kenyamanan. Jika belum siap, pilih versi lebih sederhana atau kembali ke studi orisinal tahap.</p>${playable?`<div class="score">${scoreSvg(playable)}</div><div class="example">${esc(playable.events.map(e=>`${e.notes.map(name).join('+')} (${e.duration} ketuk; R${e.fingers})`).join(' | '))}</div><p class="status-line">Penjarian kiri untuk versi satu oktaf lebih rendah: C3=5, D3=4, E3=3, F3=2, G3=1. Audio/MIDI contoh memainkan melodi kanan; mainkan versi kiri sendiri.</p>${interactive?`<div class="actions"><button data-piece="${s.playKey}">Pilih lagu di player & tuts</button><button class="outline" data-midi-download="${s.playKey}">Unduh MIDI lagu</button></div>`:`<a href="#learn/foundation/instrument">Mainkan versi pemula di chapter →</a>`}<p class="status-line">Melodi tradisional/tema Beethoven lama; susunan latihan dan MIDI dibuat khusus untuk Piano Path, bukan salinan aransemen modern. Kredit aransemen: Piano Path 2026, CC BY 4.0; sampel Salamander CC BY 3.0.</p>`:''}<p><a href="${esc(s.source)}" target="_blank" rel="noopener noreferrer">${s.source.includes('halleonard')?'Buka sumber partitur penerbit (berizin/berbayar)':'Buka sumber/katalog partitur'} ↗</a></p>${!playable?'<p class="status-line">Gunakan partitur versi yang dijelaskan. Lagu ini adalah rekomendasi repertoar eksternal; tombol contoh orisinal tahap tidak memutar lagu ini. Jika sumber menyediakan MIDI yang penggunaannya diizinkan, unduh sendiri dan buka di studio.</p>':''}</details></li>`;
 }).join('')}</ol><p class="status-line">Hak komposisi, aransemen, edisi partitur, dan rekaman terpisah. Periksa lisensi edisi yang dipilih. Lagu pop/jazz berhak cipta direkomendasikan lewat sumber penerbit; partitur/audio/MIDI penuhnya tidak disalin ke website.</p></section>`;
}
