const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{
 const {midiFixture}=await import('./tests-midi.mjs'),browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1365,height:950}}),base=process.env.PIANO_URL||'http://127.0.0.1:4182',errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{const input={id:'usb',name:'Test USB Piano',state:'connected',onmidimessage:null},access={inputs:new Map([['usb',input]]),onstatechange:null};window.testMidi={send:data=>input.onmidimessage?.({data:new Uint8Array(data)}),input,access};Object.defineProperty(navigator,'requestMIDIAccess',{value:async()=>access});window.audioStarts=0;const start=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(...args){audioStarts++;return start.apply(this,args);};});
 await page.goto(base+'/#falling');await page.locator('#piano-status').filter({hasText:'siap'}).waitFor({timeout:45000});await page.locator('#practice-usb').click();await page.locator('#midi-connect').click();await page.locator('#midi-status').filter({hasText:'Terhubung'}).waitFor();
 await page.locator('#midi-file').setInputFiles({name:'practice.mid',mimeType:'audio/midi',buffer:Buffer.from(midiFixture())});await page.locator('#song-status').filter({hasText:'3 nada'}).waitFor();assert.ok(Number(await page.locator('#falling-roll').getAttribute('data-blocks'))>0);
 await page.locator('#practice-example').uncheck();await page.locator('#song-play').click();assert.match(await page.locator('#song-time').textContent(),/Siap dalam/);await page.waitForFunction(()=>Number(document.querySelector('#falling-roll').dataset.time)>=0);await page.evaluate(()=>{testMidi.send([144,60,90]);testMidi.send([128,60,0]);});assert.match(await page.locator('#practice-score').textContent(),/Tepat 1/);assert.match(await page.locator('#practice-expression').textContent(),/Durasi: 0\/1 tepat · Dinamika USB: 1\/1 tepat/);assert.match(await page.locator('#practice-feedback').textContent(),/terlalu singkat/);
 await page.evaluate(()=>{testMidi.send([144,62,90]);testMidi.send([128,62,0]);});assert.match(await page.locator('#practice-score').textContent(),/Salah 1/);
 await page.waitForTimeout(350);assert.match(await page.locator('#practice-score').textContent(),/Terlewat 1/);await page.locator('#song-pause').click();const t=await page.locator('#falling-roll').getAttribute('data-time');await page.waitForTimeout(150);assert.equal(await page.locator('#falling-roll').getAttribute('data-time'),t);
 await page.locator('#song-stop').click();assert.match(await page.locator('#practice-score').textContent(),/Tepat 0 · Terlewat 0 · Salah 0/);await page.locator('#song-speed').selectOption('0.5');await page.locator('#song-seek').fill('1.4');await page.locator('#keyboard-size').selectOption('88');await page.locator('#keyboard-pan').fill(await page.locator('#keyboard-pan').getAttribute('max'));await page.waitForTimeout(50);assert.equal(await page.locator('#keyboard .key').count(),88);
 await page.locator('#song-play').click();await page.evaluate(()=>{testMidi.send([144,108,90]);testMidi.send([128,108,0]);});assert.match(await page.locator('#practice-score').textContent(),/Tepat 1/);await page.locator('#song-stop').click();await page.locator('#song-track').selectOption('1');await page.locator('#song-loop').check();await page.locator('#song-speed').selectOption('1.5');await page.locator('#song-play').click();await page.waitForTimeout(4100);assert.ok(Number(await page.locator("#falling-roll").getAttribute("data-time"))<0,"loop restarts with countdown");assert.equal(await page.locator('#song-play').isDisabled(),true);await page.locator('#song-stop').click();
 await page.locator('#practice-example').uncheck();const before=await page.evaluate(()=>audioStarts);await page.locator('#song-play').click();await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>audioStarts),before,'muted example produces no audio');await page.locator('#song-stop').click();await page.locator('#practice-example').check();await page.locator('#song-play').click();await page.waitForFunction(n=>audioStarts>n,before);await page.locator('#song-stop').click();
 await page.locator('#song-loop').uncheck();await page.locator('#song-speed').selectOption('1');await page.locator('#practice-example').uncheck();await page.locator('#song-play').click();await page.waitForFunction(()=>Number(document.querySelector('#falling-roll').dataset.time)>=0);await page.evaluate(()=>testMidi.send([144,60,20]));assert.match(await page.locator('#practice-feedback').textContent(),/terlalu lembut/);await page.waitForTimeout(500);await page.evaluate(()=>testMidi.send([128,60,0]));assert.match(await page.locator('#practice-expression').textContent(),/Durasi: 1\/1 tepat · Dinamika USB: 0\/1 tepat/);await page.locator('#song-stop').click();
await page.locator('#song-seek').fill('1.5');await page.locator('#song-play').click();await page.evaluate(()=>testMidi.send([144,108,90]));await page.waitForTimeout(1450);await page.evaluate(()=>testMidi.send([128,108,0]));assert.match(await page.locator('#practice-feedback').textContent(),/terlalu lama/);await page.locator('#song-stop').click();
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'work/falling-mobile.png',fullPage:true});
 await page.evaluate(()=>location.hash='studio');await page.locator('#drill-start').waitFor();assert.equal(await page.locator('#midi-device').inputValue(),'usb');await page.evaluate(()=>location.hash='falling');await page.locator('#falling-roll').waitFor();assert.equal(await page.locator('#midi-device').inputValue(),'usb');await page.evaluate(()=>testMidi.send([176,64,127]));assert.equal(await page.locator('#sustain').isChecked(),true);await page.evaluate(()=>{testMidi.input.state='disconnected';testMidi.access.onstatechange();});assert.equal(await page.locator('#sustain').isChecked(),false);
 await page.locator('#midi-file').setInputFiles({name:'bad.mid',mimeType:'audio/midi',buffer:Buffer.from([1,2,3])});assert.equal(await page.locator('#song-play').isDisabled(),true);assert.equal(await page.locator('#falling-roll').getAttribute('data-blocks'),'0');assert.deepEqual(errors,[]);await browser.close();console.log('PASS falling MIDI: canvas, timing hits/misses/errors, pause/seek/speed/loop/track, example mute, 88 keys, mobile, USB input/pedal/hotplug/route persistence and invalid file.');
})().catch(e=>{console.error(e);process.exit(1)});
