import {mutateProgress} from './progress.js';
const base=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const origins=['https://rinodu.github.io','http://127.0.0.1:4173','http://localhost:4173'];
const hex=(bytes:ArrayBuffer)=>Array.from(new Uint8Array(bytes),n=>n.toString(16).padStart(2,'0')).join('');
const digest=async(text:string)=>hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)));
async function db(path:string,method='GET',body?:unknown,prefer='return=representation'){const r=await fetch(`${base}/rest/v1/${path}`,{method,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:prefer},...(body===undefined?{}:{body:JSON.stringify(body)})});if(!r.ok)throw Error('DATABASE');const text=await r.text();return text?JSON.parse(text):null;}
function equal(a:string,b:string){if(a.length!==b.length)return false;let difference=0;for(let i=0;i<a.length;i++)difference|=a.charCodeAt(i)^b.charCodeAt(i);return difference===0;}
Deno.serve(async req=>{const origin=req.headers.get('origin')||'';const headers={'Content-Type':'application/json','Cache-Control':'no-store','Access-Control-Allow-Origin':origins.includes(origin)?origin:origins[0],'Access-Control-Allow-Headers':'content-type,authorization,apikey','Access-Control-Allow-Methods':'POST,OPTIONS',Vary:'Origin'};const reply=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers});if(origin&&!origins.includes(origin))return reply({error:'Origin tidak diizinkan.'},403);if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(req.method!=='POST')return reply({error:'Gunakan POST.'},405);
try{const text=await req.text();if(text.length>500000)return reply({error:'Permintaan terlalu besar.'},413);let b;try{b=JSON.parse(text);}catch{return reply({error:'JSON tidak valid.'},400);}if(!b||typeof b.action!=='string')return reply({error:'Aksi tidak valid.'},400);
if(b.action==='login'){if(typeof b.password!=='string'||b.password.length<6||b.password.length>128)return reply({error:'Password tidak cocok.'},401);const ip=req.headers.get('x-forwarded-for')?.split(',')[0].trim()||'unknown';const hits=await db('rpc/piano_rate_hit','POST',{bucket_key:await digest(`login:${ip}`)});if(hits>10)return reply({error:'Terlalu banyak percobaan. Tunggu 15 menit.'},429);const [access]=await db('piano_access?id=eq.1&select=salt,hash,iterations');if(!access)return reply({error:'Akses belum dikonfigurasi.'},503);const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(b.password),'PBKDF2',false,['deriveBits']);const hash=hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new Uint8Array(access.salt.match(/.{2}/g).map((s:string)=>parseInt(s,16))),iterations:access.iterations,hash:'SHA-256'},material,256));if(!equal(hash,access.hash))return reply({error:'Password tidak cocok.'},401);const token=hex(crypto.getRandomValues(new Uint8Array(32)).buffer);await db('piano_sessions','POST',{token_hash:await digest(token),expires_at:new Date(Date.now()+8*60*60*1000).toISOString()});const [p]=await db('piano_progress?id=eq.1&select=data,version');return reply({token,progress:p.data,version:p.version});}
const bearer=req.headers.get('authorization')?.replace(/^Bearer /,'')||'';if(!/^[a-f0-9]{64}$/.test(bearer))return reply({error:'Masukkan password untuk mengakses progres.'},401);const hash=await digest(bearer);const sessions=await db(`piano_sessions?token_hash=eq.${hash}&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&select=token_hash`);if(!sessions.length)return reply({error:'Sesi kedaluwarsa. Masuk kembali.'},401);if(b.action==='logout'){await db(`piano_sessions?token_hash=eq.${hash}`,'DELETE');return reply({ok:true});}const [p]=await db('piano_progress?id=eq.1&select=data,version');if(b.action==='load')return reply({progress:p.data,version:p.version});if(b.version!==p.version)return reply({error:'Progres berubah di perangkat lain. Data terbaru dimuat; ulangi tindakanmu.'},409);let data;try{data=mutateProgress(p.data,b.action,b);}catch(e){return reply({error:e.message},400);}const changed=await db(`piano_progress?id=eq.1&version=eq.${p.version}`,'PATCH',{data,version:p.version+1});if(!changed.length)return reply({error:'Progres berubah di perangkat lain. Data terbaru dimuat; ulangi tindakanmu.'},409);return reply({progress:data,version:p.version+1});
}catch(e){console.error('piano-api request failed',e instanceof Error?e.message:'unknown');return reply({error:'Server penyimpanan sedang bermasalah. Coba lagi.'},503);}});
