import {stages,blankProgress,stagePassed,canComplete} from '../course.js';
const assert=(condition,message)=>{if(!condition)throw Error(message);};
const int=(n,min,max)=>Number.isInteger(n)&&n>=min&&n<=max;
function validateStage(s){assert(s&&typeof s==='object'&&!Array.isArray(s),'Data tahap tidak valid.');const result={lessons:[],checks:[],quiz:0,rubric:[1,1,1,1],practice:false};for(const field of ['lessons','checks']){assert(Array.isArray(s[field]||[])&&(s[field]||[]).every(n=>int(n,0,2)),'Checklist tidak valid.');result[field]=[...new Set(s[field]||[])];}assert(int(s.quiz??0,0,100)&&(s.quiz??0)%20===0,'Nilai kuis tidak valid.');result.quiz=s.quiz||0;assert(Array.isArray(s.rubric||[1,1,1,1])&&(s.rubric||[1,1,1,1]).length===4&&(s.rubric||[1,1,1,1]).every(n=>int(n,1,5)),'Rubrik tidak valid.');result.rubric=s.rubric||[1,1,1,1];assert(s.practice===undefined||typeof s.practice==='boolean','Praktik tidak valid.');result.practice=s.practice===true;return result;}
function validateEntry(e,importing=false){assert(e&&int(e.stage,1,8)&&int(e.minutes,1,480)&&int(e.tempo,20,300)&&typeof e.note==='string'&&e.note.trim().length>0&&e.note.length<=2000,'Catatan tidak valid.');if(importing)assert(typeof e.id==='string'&&/^[\da-f-]{36}$/i.test(e.id)&&typeof e.date==='string'&&Number.isFinite(Date.parse(e.date)),'Identitas catatan tidak valid.');return {id:importing?e.id:crypto.randomUUID(),date:importing?e.date:new Date().toISOString(),stage:e.stage,minutes:e.minutes,tempo:e.tempo,note:e.note.trim()};}
export function mutateProgress(current,action,body){const p=structuredClone(current||blankProgress());if(action==='weekly'){assert(body.weekly&&int(body.weekly.sessions,1,7)&&int(body.weekly.minutes,10,1000),'Target mingguan tidak valid.');p.weekly={sessions:body.weekly.sessions,minutes:body.weekly.minutes};return p;}if(action==='journal'){assert(p.journal.length<1000,'Batas 1000 catatan tercapai. Ekspor cadangan terlebih dahulu.');p.journal.push(validateEntry(body.entry));return p;}if(action==='path'){assert(['pop','classical','jazz'].includes(body.path),'Jalur tidak dikenal.');p.path=body.path;return p;}if(action==='import'){const x=body.progress;if(x?.weekly){assert(int(x.weekly.sessions,1,7)&&int(x.weekly.minutes,10,1000),'Target cadangan tidak valid.');p.weekly={sessions:x.weekly.sessions,minutes:x.weekly.minutes};}assert(x&&typeof x.stages==='object'&&x.stages&&!Array.isArray(x.stages)&&Object.keys(x.stages).every(k=>/^[1-8]$/.test(k)),'Format progres tidak valid.');assert(Array.isArray(x.journal)&&x.journal.length<=1000,'Riwayat terlalu panjang.');assert(['pop','classical','jazz'].includes(x.path),'Jalur tidak valid.');for(let id=1;id<=8;id++){if(!x.stages[id])continue;assert(canComplete(p,id),'Cadangan melewati prasyarat tahap.');const a=validateStage(p.stages[id]||{}),b=validateStage(x.stages[id]);p.stages[id]={lessons:[...new Set([...a.lessons,...b.lessons])],checks:[...new Set([...a.checks,...b.checks])],quiz:Math.max(a.quiz,b.quiz),rubric:a.rubric.map((n,i)=>Math.max(n,b.rubric[i])),practice:a.practice||b.practice};}const entries=x.journal.map(e=>validateEntry(e,true));const existing=new Set(p.journal.map(e=>e.id));p.journal.push(...entries.filter(e=>{if(existing.has(e.id))return false;existing.add(e.id);return true;}));assert(p.journal.length<=1000,'Riwayat gabungan melebihi 1000 catatan.');p.path=x.path;return p;}
assert(int(body.stage,1,8),'Tahap tidak valid.');assert(canComplete(p,body.stage),'Lulus tahap sebelumnya sebelum mencatat progres tahap ini.');const earned=stagePassed(p.stages[body.stage]);const s=p.stages[body.stage]||validateStage({});if(action==='lesson'){assert(int(body.chapter,0,2),'Chapter tidak valid.');s.lessons=[...new Set([...s.lessons,body.chapter])];}else if(action==='check'){assert(int(body.index,0,2)&&typeof body.checked==='boolean','Checklist tidak valid.');s.checks=body.checked?[...new Set([...s.checks,body.index])]:s.checks.filter(n=>n!==body.index);}else if(action==='quiz'){assert(Array.isArray(body.answers)&&body.answers.length===5&&body.answers.every(n=>int(n,0,2)),'Jawab semua pertanyaan kuis.');const score=stages[body.stage-1].quiz.reduce((n,q,i)=>n+(q.answer===body.answers[i]?20:0),0);s.quiz=Math.max(s.quiz||0,score);}else if(action==='practice'){assert(Array.isArray(body.rubric)&&body.rubric.length===4&&body.rubric.every(n=>int(n,1,5))&&body.reviewed===true,'Lengkapi rubrik dan konfirmasi rekaman.');s.rubric=body.rubric;s.practice=true;}else throw Error('Aksi tidak dikenal.');
// Keep previously earned milestones when updating a later self-review.
assert(!earned||stagePassed(s),'Tahap sudah lulus. Catat evaluasi baru di jurnal agar pencapaian tetap utuh.');p.stages[body.stage]=s;return p;}
